version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 154005824457.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t work-experience-week .
      - docker tag work-experience-week:latest 154005824457.dkr.ecr.eu-north-1.amazonaws.com/work-experience-week:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 154005824457.dkr.ecr.eu-north-1.amazonaws.com/work-experience-week:latest
